server:
  port: 2222

spring:
  application:
    name: cloud-eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
