server:
  port: 2224

spring:
  application:
    name: cloud-ribbon-consumer

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
